"use strict";
require("dotenv").config();
const path=require("path");
const crypto=require("crypto");
const express=require("express");
const cors=require("cors");
const helmet=require("helmet");
const axios=require("axios");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const rateLimit=require("express-rate-limit");
const {z}=require("zod");
const app=express();
const PORT=Number(process.env.PORT||10000);
const JWT_SECRET=process.env.JWT_SECRET;
const PASSWORD_HASH=process.env.DASHBOARD_PASSWORD_HASH;
if(!JWT_SECRET) throw new Error("JWT_SECRET is required");
if(!PASSWORD_HASH) throw new Error("DASHBOARD_PASSWORD_HASH is required");
app.disable("x-powered-by");
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(express.json({limit:"100kb"}));
app.use(cors({origin:true,methods:["GET","POST"],allowedHeaders:["Content-Type","Authorization"]}));
const loginLimiter=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:true,legacyHeaders:false});
const apiLimiter=rateLimit({windowMs:60*1000,limit:30,standardHeaders:true,legacyHeaders:false});
const http=axios.create({timeout:Number(process.env.CHIRON_TIMEOUT_MS||15000),validateStatus:()=>true});
let tokenCache={value:null,expiresAt:0};
const tripSchema=z.object({trip_id:z.string().trim().min(1).max(200),start_time:z.string().trim().min(1).max(100),end_time:z.string().trim().min(1).max(100),departure:z.string().trim().min(1).max(2000),destination:z.string().trim().min(1).max(2000),departure_lat:z.number().finite().optional(),departure_lng:z.number().finite().optional(),destination_lat:z.number().finite().optional(),destination_lng:z.number().finite().optional(),distance_km:z.number().finite().nonnegative().optional(),fare:z.number().finite().nonnegative().optional()});
const requestSchema=z.object({chiron_id:z.string().trim().min(1).max(100),kbo:z.string().trim().min(1).max(100),driver_card:z.string().trim().min(1).max(100),license_plate:z.string().trim().min(1).max(100),trips:z.array(tripSchema).min(1).max(50)});
const id=()=>crypto.randomUUID();
function auth(req,res,next){const [scheme,token]=(req.get("authorization")||"").split(" ");if(scheme!=="Bearer"||!token)return res.status(401).json({status:"ERROR",bericht:"التوكن مفقود"});try{req.user=jwt.verify(token,JWT_SECRET,{algorithms:["HS256"],issuer:"chiron-taxi",audience:"chiron-dashboard"});next()}catch{return res.status(403).json({status:"ERROR",bericht:"التوكن غير صالح"})}}
async function getToken(){if(tokenCache.value&&Date.now()<tokenCache.expiresAt-60000)return tokenCache.value;const url=process.env.CHIRON_TOKEN_URL;if(!url||!process.env.CHIRON_CLIENT_ID||!process.env.CHIRON_CLIENT_SECRET)throw new Error("Chiron OAuth settings are incomplete");const form=new URLSearchParams({grant_type:"client_credentials"});if(process.env.CHIRON_SCOPE)form.set("scope",process.env.CHIRON_SCOPE);const r=await http.post(url,form.toString(),{auth:{username:process.env.CHIRON_CLIENT_ID,password:process.env.CHIRON_CLIENT_SECRET},headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"}});if(r.status<200||r.status>=300)throw new Error(`OAuth failed ${r.status}: ${JSON.stringify(r.data)}`);if(!r.data?.access_token)throw new Error("No access_token returned");tokenCache={value:r.data.access_token,expiresAt:Date.now()+Number(r.data.expires_in||3600)*1000};return tokenCache.value}
app.get("/health",(req,res)=>res.json({status:"OK",service:"chiron-taxi",environment:process.env.NODE_ENV||"development"}));
app.post("/api/login",loginLimiter,async(req,res)=>{const p=z.object({password:z.string().min(1).max(500)}).safeParse(req.body);if(!p.success)return res.status(400).json({status:"ERROR",bericht:"بيانات الدخول غير صحيحة"});if(!await bcrypt.compare(p.data.password,PASSWORD_HASH))return res.status(401).json({status:"ERROR",bericht:"كلمة المرور غير صحيحة"});const token=jwt.sign({role:"admin"},JWT_SECRET,{algorithm:"HS256",expiresIn:"12h",issuer:"chiron-taxi",audience:"chiron-dashboard"});res.json({status:"SUCCESS",token})});
app.get("/api/chiron/health",auth,async(req,res)=>{const request_id=id();try{const token=await getToken();res.json({status:"SUCCESS",request_id,environment:process.env.CHIRON_ENV||"unknown",token_received:Boolean(token)})}catch(e){console.error(request_id,e.message);res.status(502).json({status:"ERROR",request_id,bericht:"فشل اتصال Chiron",details:process.env.NODE_ENV==="production"?undefined:e.message})}});
app.post("/api/chiron/trips",apiLimiter,auth,async(req,res)=>{const request_id=id();const parsed=requestSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({status:"ERROR",request_id,bericht:"بيانات الرحلات غير صحيحة",details:parsed.error.flatten()});try{const token=await getToken();const url=process.env.CHIRON_API_URL;if(!url)throw new Error("CHIRON_API_URL is missing");const r=await http.post(url,parsed.data,{headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",Accept:"application/json","X-Request-ID":request_id}});if(r.status<200||r.status>=300){console.error(request_id,r.status,r.data);return res.status(502).json({status:"ERROR",request_id,bericht:"Chiron رفض الطلب",chiron_status:r.status,details:process.env.NODE_ENV==="production"?undefined:r.data})}res.json({status:"SUCCESS",request_id,bericht:"تم إرسال الطلب إلى Chiron",chiron_status:r.status,chiron_data:r.data})}catch(e){console.error(request_id,e.response?.data||e.message);res.status(502).json({status:"ERROR",request_id,bericht:"فشل الاتصال بخدمة Chiron",details:process.env.NODE_ENV==="production"?"خطأ داخلي":e.message})}});
app.use(express.static(path.join(__dirname,"public")));
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,"0.0.0.0",()=>console.log(`Listening on ${PORT}`));
